In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Assignment 2/diabetes.csv')
# df = pd.read_csv('/kaggle/input/diabetes-dataset/diabetes.csv')

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
mmsc=MinMaxScaler()
ndf=mmsc.fit_transform(df)

In [ ]:
ndf.flatten()

array([0.35294118, 0.74371859, 0.59016393, ..., 0.10119556, 0.03333333,
       0.        ])

In [ ]:
ss=StandardScaler()
sdf=ss.fit_transform(df)

In [ ]:
sdf.flatten()

array([ 0.63994726,  0.84832379,  0.14964075, ..., -0.47378505,
       -0.87137393, -0.73212021])

In [ ]:
sdf.flatten().mean()

8.326672684688674e-17

In [ ]:
sdf.flatten().std()

0.9999999999999999

In [ ]:
pd.DataFrame(ndf)

0         1         2         3         4         5         6  \
0    0.352941  0.743719  0.590164  0.353535  0.000000  0.500745  0.234415   
1    0.058824  0.427136  0.540984  0.292929  0.000000  0.396423  0.116567   
2    0.470588  0.919598  0.524590  0.000000  0.000000  0.347243  0.253629   
3    0.058824  0.447236  0.540984  0.232323  0.111111  0.418778  0.038002   
4    0.000000  0.688442  0.327869  0.353535  0.198582  0.642325  0.943638   
..        ...       ...       ...       ...       ...       ...       ...   
763  0.588235  0.507538  0.622951  0.484848  0.212766  0.490313  0.039710   
764  0.117647  0.613065  0.573770  0.272727  0.000000  0.548435  0.111870   
765  0.294118  0.608040  0.590164  0.232323  0.132388  0.390462  0.071307   
766  0.058824  0.633166  0.491803  0.000000  0.000000  0.448584  0.115713   
767  0.058824  0.467337  0.573770  0.313131  0.000000  0.453055  0.101196   

            7    8  
0    0.483333  1.0  
1    0.166667  0.0  
2    0.183333  1.0  
3    0.000000  0.0  
4    0.200000  1.0  
..        ...  ...  
763  0.700000  0.0  
764  0.100000  0.0  
765  0.150000  0.0  
766  0.433333  1.0  
767  0.033333  0.0  

[768 rows x 9 columns]

In [ ]:
pd.DataFrame(sdf)

0         1         2         3         4         5         6  \
0    0.639947  0.848324  0.149641  0.907270 -0.692891  0.204013  0.468492   
1   -0.844885 -1.123396 -0.160546  0.530902 -0.692891 -0.684422 -0.365061   
2    1.233880  1.943724 -0.263941 -1.288212 -0.692891 -1.103255  0.604397   
3   -0.844885 -0.998208 -0.160546  0.154533  0.123302 -0.494043 -0.920763   
4   -1.141852  0.504055 -1.504687  0.907270  0.765836  1.409746  5.484909   
..        ...       ...       ...       ...       ...       ...       ...   
763  1.827813 -0.622642  0.356432  1.722735  0.870031  0.115169 -0.908682   
764 -0.547919  0.034598  0.046245  0.405445 -0.692891  0.610154 -0.398282   
765  0.342981  0.003301  0.149641  0.154533  0.279594 -0.735190 -0.685193   
766 -0.844885  0.159787 -0.470732 -1.288212 -0.692891 -0.240205 -0.371101   
767 -0.844885 -0.873019  0.046245  0.656358 -0.692891 -0.202129 -0.473785   

            7         8  
0    1.425995  1.365896  
1   -0.190672 -0.732120  
2   -0.105584  1.365896  
3   -1.041549 -0.732120  
4   -0.020496  1.365896  
..        ...       ...  
763  2.532136 -0.732120  
764 -0.531023 -0.732120  
765 -0.275760 -0.732120  
766  1.170732  1.365896  
767 -0.871374 -0.732120  

[768 rows x 9 columns]

# **`Imputation`**


In [ ]:
from sklearn.impute import SimpleImputer, KNNImputer

In [ ]:
sim = SimpleImputer(missing_values=0, strategy='median')

In [ ]:
simdf=sim.fit_transform(df)

In [ ]:
simdf

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   1.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   1.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   1.   ]])

In [ ]:
kdf = KNNImputer(missing_values=0,n_neighbors=5,weights='uniform')

In [ ]:
kdf.fit_transform(df)

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   1.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   1.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   1.   ]])

# **`Encoding`**

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

In [ ]:
odf = OneHotEncoder(sparse_output=False)
odf

OneHotEncoder(sparse_output=False)

In [ ]:
df['Age'].value_counts()

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
38    16
36    16
32    16
45    15
34    14
46    13
43    13
40    13
39    12
35    10
50     8
51     8
52     8
44     8
58     7
47     6
54     6
49     5
48     5
57     5
53     5
60     5
66     4
63     4
62     4
55     4
67     3
56     3
59     3
65     3
69     2
61     2
72     1
81     1
64     1
70     1
68     1
Name: count, dtype: int64

In [ ]:
encod = odf.fit_transform(df['Age'].values.reshape(-1, 1))

In [ ]:
print(odf.fit_transform(df['Age'].values.reshape(-1, 1)))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [ ]:
odf.get_feature_names_out()

array(['x0_21', 'x0_22', 'x0_23', 'x0_24', 'x0_25', 'x0_26', 'x0_27',
       'x0_28', 'x0_29', 'x0_30', 'x0_31', 'x0_32', 'x0_33', 'x0_34',
       'x0_35', 'x0_36', 'x0_37', 'x0_38', 'x0_39', 'x0_40', 'x0_41',
       'x0_42', 'x0_43', 'x0_44', 'x0_45', 'x0_46', 'x0_47', 'x0_48',
       'x0_49', 'x0_50', 'x0_51', 'x0_52', 'x0_53', 'x0_54', 'x0_55',
       'x0_56', 'x0_57', 'x0_58', 'x0_59', 'x0_60', 'x0_61', 'x0_62',
       'x0_63', 'x0_64', 'x0_65', 'x0_66', 'x0_67', 'x0_68', 'x0_69',
       'x0_70', 'x0_72', 'x0_81'], dtype=object)

In [ ]:
encoded_df = pd.DataFrame(encod, columns=odf.get_feature_names_out())

In [ ]:
encoded_df

x0_21  x0_22  x0_23  x0_24  x0_25  x0_26  x0_27  x0_28  x0_29  x0_30  \
0      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3      1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
763    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
764    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0   
765    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
766    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
767    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

     ...  x0_63  x0_64  x0_65  x0_66  x0_67  x0_68  x0_69  x0_70  x0_72  x0_81  
0    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
763  ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
764  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
765  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
766  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
767  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[768 rows x 52 columns]

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [ ]:
df.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
nf= ['Pregnancies', 'BloodPressure']
cf=['Age','Outcome']

In [ ]:
nft = Pipeline(
    steps = [
        ('imputation', SimpleImputer(strategy='mean')),
        ('scaling', StandardScaler())
    ]
)

In [ ]:
cft = Pipeline(
    steps = [
        ('imputation', SimpleImputer(strategy='most_frequent')),
        ('encoding', OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [ ]:
t = ColumnTransformer(
    transformers = [
        ('nt', nft, nf),
    ]
)

In [ ]:
Xp = t.fit_transform(df)

In [ ]:
print(Xp)

[[ 0.63994726  0.14964075]
 [-0.84488505 -0.16054575]
 [ 1.23388019 -0.26394125]
 ...
 [ 0.3429808   0.14964075]
 [-0.84488505 -0.47073225]
 [-0.84488505  0.04624525]]


In [ ]:
print("Shape of Xp:", Xp.shape)
print("Length of feature_names:", len(feature_names))


Shape of Xp: (768, 2)
Length of feature_names: 56


In [ ]:
print("Feature names:", feature_names)


Feature names: ['Pregnancies', 'BloodPressure', 'x0_21', 'x0_22', 'x0_23', 'x0_24', 'x0_25', 'x0_26', 'x0_27', 'x0_28', 'x0_29', 'x0_30', 'x0_31', 'x0_32', 'x0_33', 'x0_34', 'x0_35', 'x0_36', 'x0_37', 'x0_38', 'x0_39', 'x0_40', 'x0_41', 'x0_42', 'x0_43', 'x0_44', 'x0_45', 'x0_46', 'x0_47', 'x0_48', 'x0_49', 'x0_50', 'x0_51', 'x0_52', 'x0_53', 'x0_54', 'x0_55', 'x0_56', 'x0_57', 'x0_58', 'x0_59', 'x0_60', 'x0_61', 'x0_62', 'x0_63', 'x0_64', 'x0_65', 'x0_66', 'x0_67', 'x0_68', 'x0_69', 'x0_70', 'x0_72', 'x0_81', 'x1_0', 'x1_1']
