In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [11]:
X, y = make_classification(n_samples=100, n_features=2, n_redundant=0, n_classes=3, n_clusters_per_class=1)

In [12]:
X

array([[ 1.91973148e+00, -1.65779355e+00],
       [-1.45188513e+00,  1.12503725e+00],
       [ 1.16335626e+00,  8.94212314e-01],
       [-1.59006161e+00,  1.03967979e+00],
       [ 2.22810068e+00, -1.57396482e+00],
       [-8.57282868e-01,  1.03342215e+00],
       [ 1.83760060e-01,  5.77348849e-01],
       [ 2.05327612e+00,  1.82277620e+00],
       [ 5.42696653e-01, -6.68356734e-01],
       [ 1.59533756e+00, -1.33048932e+00],
       [-8.43637852e-01,  3.47227305e-02],
       [ 1.08732071e+00, -9.14867412e-01],
       [ 1.14876607e+00,  1.57899915e-01],
       [ 2.37530913e+00, -1.69323258e+00],
       [ 2.61496106e+00, -1.86337328e+00],
       [ 2.55924888e+00, -2.66295507e+00],
       [-3.36618297e-01, -6.76119806e-01],
       [ 1.66120540e-01, -7.71725038e-01],
       [ 4.63551218e-01,  1.57432827e+00],
       [ 2.73836549e+00,  1.49231939e+00],
       [-8.23702487e-01,  1.06806789e+00],
       [ 9.73111318e-01, -8.87230568e-02],
       [ 1.65918895e-01,  3.48509053e-01],
       [ 3.

In [13]:
y

array([1, 0, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 0, 2,
       2, 0, 1, 2, 0, 2, 0, 1, 1, 0, 1, 2, 0, 1, 0, 2, 2, 1, 0, 0, 0, 2,
       0, 0, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1,
       2, 2, 1, 1, 2, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0, 2, 1, 1, 0, 0, 0, 0,
       0, 2, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [15]:
len(X_train), len(X_test), len(y_train), len(y_test)

(90, 10, 90, 10)

In [21]:
knn = KNeighborsClassifier(n_neighbors=3)

In [22]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [23]:
y_pred = knn.predict(X_test)

In [24]:
y_pred

array([2, 0, 1, 2, 2, 1, 0, 1, 0, 1])

In [25]:
y_test

array([2, 0, 1, 2, 2, 2, 0, 1, 0, 1])

In [27]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9


In [34]:
import numpy as np

In [35]:
from sklearn.linear_model import LinearRegression

In [40]:
x = np.array([1, 2, 3, 4]).reshape(-1, 1)
y = [3, 5, 7, 9]

In [41]:
x

array([[1],
       [2],
       [3],
       [4]])

In [42]:
linreg = LinearRegression()
linreg.fit(x, y)

LinearRegression()

In [43]:
linreg.coef_

array([2.])

In [44]:
linreg.intercept_

0.9999999999999982

In [47]:
linreg.predict([[5]])

array([11.])

In [48]:
X = [[1, 2], [2, 3], [3, 4], [4, 5]]
y = [3, 4, 5, 6]

In [49]:
mreg = LinearRegression()
mreg.fit(X, y)

LinearRegression()

In [50]:
mreg.intercept_

1.4999999999999991

In [51]:
mreg.coef_

array([0.5, 0.5])

In [52]:
pred = mreg.predict([[5, 6], [6, 7], [7, 8]])

In [53]:
pred

array([7., 8., 9.])

In [54]:
# Polynomial Regression

In [69]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [70]:
x = np.array([1, 2, 3, 4]).reshape(-1, 1)
y = np.array([2, 5, 10, 17])

In [71]:
transformer = PolynomialFeatures(degree=2)
x_transformed = transformer.fit_transform(x)

In [72]:
x_transformed

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.]])

In [73]:
model = LinearRegression().fit(x_transformed, y)

In [76]:
pred = model.predict(transformer.transform([[5], [6], [7]]))

In [77]:
pred

array([26., 37., 50.])