In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
ra = np.random.randint(1, 101, size=100)
ra

array([ 10,  51,  72,  71,  64,  92,  49,  85,  36,  26,  64,  45,  43,
        78,  76,  41,  38,  37,  30,   5,  16,  93,   1,  38, 100,  66,
        34,   6,  57,  85,  67,  71,  71,   6,  97,  64,  52,   2,  79,
        37, 100,  63,  14,   9,  45,  83,   8,  75,  97,  18,  35,  31,
        63,  13,   5,  37,  71,  98,  88,  65,  97,  72,  68,  11,  23,
        98,  88,  69,  96,  95,  19,  69,  21,  11,  20,  16,  89,   5,
        33,   2,   1,   2,  92,  87,  32,  45,  27,  49,  89,  17,  93,
        16,  16,  46,  52,  75,  39,  12,  93,  52])

In [3]:
ra = ra.reshape(-1, 1)    # Converts 1-D array to 2-D array column majorly

In [4]:
mmsc = MinMaxScaler()
normalized_array = mmsc.fit_transform(ra)

In [5]:
normalized_array.flatten()

array([0.09090909, 0.50505051, 0.71717172, 0.70707071, 0.63636364,
       0.91919192, 0.48484848, 0.84848485, 0.35353535, 0.25252525,
       0.63636364, 0.44444444, 0.42424242, 0.77777778, 0.75757576,
       0.4040404 , 0.37373737, 0.36363636, 0.29292929, 0.04040404,
       0.15151515, 0.92929293, 0.        , 0.37373737, 1.        ,
       0.65656566, 0.33333333, 0.05050505, 0.56565657, 0.84848485,
       0.66666667, 0.70707071, 0.70707071, 0.05050505, 0.96969697,
       0.63636364, 0.51515152, 0.01010101, 0.78787879, 0.36363636,
       1.        , 0.62626263, 0.13131313, 0.08080808, 0.44444444,
       0.82828283, 0.07070707, 0.74747475, 0.96969697, 0.17171717,
       0.34343434, 0.3030303 , 0.62626263, 0.12121212, 0.04040404,
       0.36363636, 0.70707071, 0.97979798, 0.87878788, 0.64646465,
       0.96969697, 0.71717172, 0.67676768, 0.1010101 , 0.22222222,
       0.97979798, 0.87878788, 0.68686869, 0.95959596, 0.94949495,
       0.18181818, 0.68686869, 0.2020202 , 0.1010101 , 0.19191

In [6]:
ss = StandardScaler()
standardized_array = ss.fit_transform(ra)

In [7]:
standardized_array.flatten()

array([-1.28294549,  0.02879429,  0.700661  ,  0.66866735,  0.44471178,
        1.34053406, -0.03519302,  1.11657849, -0.45111051, -0.77104704,
        0.44471178, -0.16316763, -0.22715494,  0.89262292,  0.82863561,
       -0.29114224, -0.3871232 , -0.41911686, -0.64307243, -1.44291375,
       -1.09098357,  1.37252772, -1.57088837, -0.3871232 ,  1.59648329,
        0.50869908, -0.51509781, -1.4109201 ,  0.22075621,  1.11657849,
        0.54069274,  0.66866735,  0.66866735, -1.4109201 ,  1.50050233,
        0.44471178,  0.06078794, -1.53889471,  0.92461657, -0.41911686,
        1.59648329,  0.41271812, -1.15497088, -1.31493914, -0.16316763,
        1.05259119, -1.3469328 ,  0.79664196,  1.50050233, -1.02699626,
       -0.48310416, -0.61107877,  0.41271812, -1.18696453, -1.44291375,
       -0.41911686,  0.66866735,  1.53249598,  1.21255945,  0.47670543,
        1.50050233,  0.700661  ,  0.57268639, -1.25095184, -0.867028  ,
        1.53249598,  1.21255945,  0.60468004,  1.46850868,  1.43

In [8]:
data = np.random.randint(1, 100, size=(100, 100))

In [9]:
data

array([[86, 43, 23, ..., 65,  1, 10],
       [47, 39, 24, ..., 60, 96, 74],
       [48, 48, 76, ..., 26,  8, 57],
       ...,
       [20, 73, 54, ..., 18, 34, 39],
       [59, 82, 25, ..., 88, 27, 26],
       [78, 96, 26, ..., 18, 57, 27]])

In [10]:
df = pd.DataFrame(data)

In [11]:
df

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
0   86  43  23   5  74  62  80  42  45   9  ...  26  60  63   1  27  11  53   
1   47  39  24  72  26  75  65  74   8  17  ...  36  46  35  91  88  65  97   
2   48  48  76  28  77  48  55  57  89  81  ...  87  47  85  65  66  22  72   
3   88  95  23  58  11  62  36  30  54  79  ...  78  41  38  19  57  47  87   
4   37  28  14  14  31  97  52  68  23  31  ...  93  15  15  82  84  38  28   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
95  52  20   1  82   6  87  91  37  52  45  ...  45   8  57  73  79  86  30   
96  31  53  63  17  71  80  65  86  49  88  ...  78  89  54  51  68  52  62   
97  20  73  54  61  90   4  93  96  25  20  ...  30  80  29  88  95  40  49   
98  59  82  25  50  72  25  45  37  61  86  ...  79  83  91  62  37  75   3   
99  78  96  26  42  64  76   5  44  38  88  ...  55   5  59  34  73  88  96   

    97  98  99  
0   65   1  10  
1   60  96  74  
2   26   8  57  
3   66  92  42  
4   60  26  67  
..  ..  ..  ..  
95  98  55  29  
96  31  61  50  
97  18  34  39  
98  88  27  26  
99  18  57  27  

[100 rows x 100 columns]

In [12]:
mmsc = MinMaxScaler()
normalized_df = mmsc.fit_transform(df)

In [13]:
pd.DataFrame(normalized_df)

0         1         2         3         4         5         6   \
0   0.867347  0.427083  0.224490  0.041237  0.744898  0.622449  0.815217   
1   0.469388  0.385417  0.234694  0.731959  0.255102  0.755102  0.652174   
2   0.479592  0.479167  0.765306  0.278351  0.775510  0.479592  0.543478   
3   0.887755  0.968750  0.224490  0.587629  0.102041  0.622449  0.336957   
4   0.367347  0.270833  0.132653  0.134021  0.306122  0.979592  0.510870   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.520408  0.187500  0.000000  0.835052  0.051020  0.877551  0.934783   
96  0.306122  0.531250  0.632653  0.164948  0.714286  0.806122  0.652174   
97  0.193878  0.739583  0.540816  0.618557  0.908163  0.030612  0.956522   
98  0.591837  0.833333  0.244898  0.505155  0.724490  0.244898  0.434783   
99  0.785714  0.979167  0.255102  0.422680  0.642857  0.765306  0.000000   

          7         8         9   ...        90        91        92        93  \
0   0.418367  0.437500  0.081633  ...  0.255102  0.608247  0.639175  0.000000   
1   0.744898  0.052083  0.163265  ...  0.357143  0.463918  0.350515  0.918367   
2   0.571429  0.895833  0.816327  ...  0.877551  0.474227  0.865979  0.653061   
3   0.295918  0.531250  0.795918  ...  0.785714  0.412371  0.381443  0.183673   
4   0.683673  0.208333  0.306122  ...  0.938776  0.144330  0.144330  0.826531   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.367347  0.510417  0.448980  ...  0.448980  0.072165  0.577320  0.734694   
96  0.867347  0.479167  0.887755  ...  0.785714  0.907216  0.546392  0.510204   
97  0.969388  0.229167  0.193878  ...  0.295918  0.814433  0.288660  0.887755   
98  0.367347  0.604167  0.867347  ...  0.795918  0.845361  0.927835  0.622449   
99  0.438776  0.364583  0.887755  ...  0.551020  0.041237  0.597938  0.336735   

          94        95        96        97        98        99  
0   0.265306  0.106383  0.525773  0.649485  0.000000  0.095745  
1   0.887755  0.680851  0.979381  0.597938  0.979381  0.776596  
2   0.663265  0.223404  0.721649  0.247423  0.072165  0.595745  
3   0.571429  0.489362  0.876289  0.659794  0.938144  0.436170  
4   0.846939  0.393617  0.268041  0.597938  0.257732  0.702128  
..       ...       ...       ...       ...       ...       ...  
95  0.795918  0.904255  0.288660  0.989691  0.556701  0.297872  
96  0.683673  0.542553  0.618557  0.298969  0.618557  0.521277  
97  0.959184  0.414894  0.484536  0.164948  0.340206  0.404255  
98  0.367347  0.787234  0.010309  0.886598  0.268041  0.265957  
99  0.734694  0.925532  0.969072  0.164948  0.577320  0.276596  

[100 rows x 100 columns]

In [14]:
ss = StandardScaler()
standardized_df = ss.fit_transform(df)

In [15]:
pd.DataFrame(standardized_df)

0         1         2         3         4         5         6   \
0   1.160299 -0.338131 -0.805158 -1.395595  0.893196  0.374523  0.980188   
1  -0.164398 -0.477566 -0.770808  0.912597 -0.735733  0.810796  0.452638   
2  -0.130432 -0.163837  1.015378 -0.603230  0.995004 -0.095309  0.100938   
3   1.228232  1.474530 -0.805158  0.430288 -1.244773  0.374523 -0.567292   
4  -0.504064 -0.861014 -1.114305 -1.085539 -0.566053  1.549103 -0.004572   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.005435 -1.139885 -1.560852  1.257103 -1.414453  1.213509  1.367059   
96 -0.707864  0.010458  0.568832 -0.982187  0.791388  0.978593  0.452638   
97 -1.081496  0.707635  0.259684  0.533640  1.436172 -1.571923  1.437399   
98  0.243201  1.021365 -0.736458  0.154683  0.825324 -0.867175 -0.250762   
99  0.888566  1.509389 -0.702109 -0.120922  0.553836  0.844355 -1.657563   

          7         8         9   ...        90        91        92        93  \
0  -0.086923 -0.255733 -1.469872  ... -0.913344  0.376805  0.442351 -1.891515   
1   0.982898 -1.776974 -1.192013  ... -0.542066 -0.103201 -0.590662  1.518668   
2   0.414556  1.553311  1.030855  ...  1.351452 -0.068915  1.254005  0.533504   
3  -0.488106  0.114299  0.961391  ...  1.017302 -0.274633 -0.479982 -1.209478   
4   0.782307 -1.160255 -0.705761  ...  1.574219 -1.166074 -1.328529  1.177650   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95 -0.254083  0.032069 -0.219508  ... -0.207916 -1.406077  0.220991  0.836632   
96  1.384081 -0.091274  1.273982  ...  1.017302  1.371105  0.110311  0.003031   
97  1.718401 -1.078025 -1.087816  ... -0.764833  1.062530 -0.812022  1.404995   
98 -0.254083  0.402101  1.204517  ...  1.054430  1.165388  1.475365  0.419831   
99 -0.020059 -0.543535  1.273982  ...  0.163362 -1.508936  0.294778 -0.641114   

          94        95        96        97        98        99  
0  -0.910219 -1.373052  0.087794  0.608661 -1.480878 -1.559643  
1   1.214671  0.498346  1.620710  0.424107  1.696971  0.894072  
2   0.448317 -0.991841  0.749735 -0.830865 -1.246720  0.242304  
3   0.134809 -0.125453  1.272320  0.645572  1.563167 -0.332785  
4   1.075334 -0.437353 -0.783180  0.424107 -0.644602  0.625697  
..       ...       ...       ...       ...       ...       ...  
95  0.901162  1.226113 -0.713502  1.826722  0.325479 -0.831196  
96  0.517985  0.047825  0.401345 -0.646310  0.526185 -0.026071  
97  1.458510 -0.368042 -0.051562 -1.126152 -0.376993 -0.447803  
98 -0.561877  0.844902 -1.654155  1.457613 -0.611151 -0.946214  
99  0.692157  1.295424  1.585871 -1.126152  0.392381 -0.907875  

[100 rows x 100 columns]

In [16]:
standardized_df[0].mean(), standardized_df[0].std() 

(-0.1329261493225075, 1.0233013549076324)

In [17]:
standardized_df[1].mean(), standardized_df[1].std()

(0.10898621747352538, 1.0133273753943957)

In [18]:
df = pd.DataFrame([[1, 2], [3, np.nan]])

In [19]:
df

0    1
0  1  2.0
1  3  NaN

In [20]:
df.isna()

0      1
0  False  False
1  False   True

In [21]:
from sklearn.impute import SimpleImputer, KNNImputer

In [22]:
d = [[7, 2, 3], [4, np.nan, 6], [10, 5, 9]]

In [23]:
sim = SimpleImputer(missing_values=np.nan, strategy='mean')

In [24]:
d = sim.fit_transform(d)

In [25]:
d

array([[ 7. ,  2. ,  3. ],
       [ 4. ,  3.5,  6. ],
       [10. ,  5. ,  9. ]])

In [26]:
d.mean(axis=0)

array([7. , 3.5, 6. ])

In [27]:
e = [[np.nan, 2, 3], [6, np.nan, 6], [10, 5, np.nan]]

In [28]:
e = sim.transform(e)

In [29]:
e

array([[ 7. ,  2. ,  3. ],
       [ 6. ,  3.5,  6. ],
       [10. ,  5. ,  6. ]])

In [30]:
d = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]

In [31]:
knnimputer = KNNImputer(n_neighbors=3)

In [32]:
knnimputer.fit_transform(d)

array([[1., 2., 5.],
       [3., 4., 3.],
       [4., 6., 5.],
       [8., 8., 7.]])

In [33]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

In [34]:
df = pd.DataFrame({'category': ['A', 'B', 'C', 'A', 'C']})

In [35]:
df

category
0        A
1        B
2        C
3        A
4        C

In [36]:
ohe = OneHotEncoder(sparse_output=False)

In [37]:
encoded_data = ohe.fit_transform(df['category'].values.reshape(-1, 1))

In [38]:
print(ohe.fit_transform(df['category'].values.reshape(-1, 1)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [39]:
ohe.get_feature_names_out()

array(['x0_A', 'x0_B', 'x0_C'], dtype=object)

In [40]:
encoded_df = pd.DataFrame(encoded_data, columns=ohe.get_feature_names_out())

In [41]:
encoded_df

x0_A  x0_B  x0_C
0   1.0   0.0   0.0
1   0.0   1.0   0.0
2   0.0   0.0   1.0
3   1.0   0.0   0.0
4   0.0   0.0   1.0

In [42]:
le = LabelEncoder()

In [43]:
le.fit_transform(df['category'])

array([0, 1, 2, 0, 2])

In [44]:
df

category
0        A
1        B
2        C
3        A
4        C

In [45]:
df = pd.DataFrame({'category': ['small', 'medium', 'large', 'medium', 'small']})

In [46]:
order = ['small', 'medium', 'large']

In [47]:
oe = OrdinalEncoder(categories=[order])

In [48]:
oe.fit_transform(df['category'].values.reshape(-1, 1))

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.]])

In [49]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [50]:
# Dummy data
data = {
    'age': [25, 30, 35, None, 40],
    'income': [50000, 60000, None, 70000, 80000],
    'gender': ['M', 'F', 'F', 'M', 'M'],
    'education': ['Bachelor', 'Master', 'PhD', 'Master', 'Bachelor'],
    'target': [0, 1, 0, 1, 1]
}

df = pd.DataFrame(data)

df.head()

age   income gender education  target
0  25.0  50000.0      M  Bachelor       0
1  30.0  60000.0      F    Master       1
2  35.0      NaN      F       PhD       0
3   NaN  70000.0      M    Master       1
4  40.0  80000.0      M  Bachelor       1

In [51]:
X = df.drop('target', axis=1)

In [52]:
X

age   income gender education
0  25.0  50000.0      M  Bachelor
1  30.0  60000.0      F    Master
2  35.0      NaN      F       PhD
3   NaN  70000.0      M    Master
4  40.0  80000.0      M  Bachelor

In [53]:
numeric_features = ['age', 'income']
categorical_features = ['gender', 'education']

In [57]:
# Numeric Transformer
numeric_transformer = Pipeline(
    steps = [
        ('imputation', SimpleImputer(strategy='median')),
        ('scaling', StandardScaler())
    ]
)

In [58]:
# Categorical Transfomer
categorical_transformer = Pipeline(
    steps = [
        ('imputation', SimpleImputer(strategy='most_frequent')),
        ('encoding', OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [66]:
transformer = ColumnTransformer(
    transformers = [
        ('numeric_transformations', numeric_transformer, numeric_features),
        ('categorical_transformations', categorical_transformer, categorical_features)
    ]
)

In [67]:
X_processed = transformer.fit_transform(X)

In [68]:
X_processed

array([[-1.5, -1.5,  0. ,  1. ,  1. ,  0. ,  0. ],
       [-0.5, -0.5,  1. ,  0. ,  0. ,  1. ,  0. ],
       [ 0.5,  0. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [ 0. ,  0.5,  0. ,  1. ,  0. ,  1. ,  0. ],
       [ 1.5,  1.5,  0. ,  1. ,  1. ,  0. ,  0. ]])

In [75]:
dir(transformer)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_add_prefix_for_feature_names_out',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_columns',
 '_fit_transform',
 '_get_default_requests',
 '_get_feature_name_out_for_transformer',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params',
 '_get_tags',
 '_hstack',
 '_iter',
 '_log_message',
 '_more_tags',
 '_n_features',
 '_name_to_fitted_passthrough',
 '_parameter_constraints',
 '_record_output_indices',
 '_remainder',
 '_replace_estimator',
 '_repr_html_',
 '_repr_htm

In [73]:
df = pd.DataFrame(X_processed, columns = list(numeric_features) + list(transformer.named_transformers_['categorical_transformations']['encoding'].get_feature_names_out()))

In [74]:
df

age  income  x0_F  x0_M  x1_Bachelor  x1_Master  x1_PhD
0 -1.5    -1.5   0.0   1.0          1.0        0.0     0.0
1 -0.5    -0.5   1.0   0.0          0.0        1.0     0.0
2  0.5     0.0   1.0   0.0          0.0        0.0     1.0
3  0.0     0.5   0.0   1.0          0.0        1.0     0.0
4  1.5     1.5   0.0   1.0          1.0        0.0     0.0